import { useEffect, useMemo, useState } from 'react';
import type { DiagnosticCommand, DiagnosticSnapshot } from '../../electron/preload/contracts';

const pct=(n:number)=>`${Math.round(n*100)}%`;
const send=(command:DiagnosticCommand)=>window.pokoloko.sendWindowCommand({type:'diagnostics_command',command});
export function DiagnosticControlPanel(){
 const [snapshot,setSnapshot]=useState<DiagnosticSnapshot|null>(null); const [seed,setSeed]=useState('1347373903'); const [mindKey,setMindKey]=useState('energy'); const [mindValue,setMindValue]=useState(.5); const [showGuides,setShowGuides]=useState(true);
 useEffect(() => { let active = true; const poll = (): void => { void window.pokoloko.getDiagnosticSnapshot().then((v) => { if (active) setSnapshot(v); }).catch((): void => {}); }; poll(); const id = setInterval(poll, 250); return (): void => { active = false; clearInterval(id); }; }, []);
 const events=useMemo(()=>snapshot?.trace.slice(-80).reverse()??[],[snapshot]);
 if(!snapshot)return <main className="diagnostic-console"><p>Connecting to the living runtimeâ€¦</p></main>;
 const r=snapshot.runtime,p=snapshot.presentation,sm=snapshot.stateMachine;
 return <main className="diagnostic-console">
  <header className="diagnostic-header"><div><p className="settings-kicker">Developer diagnostic mode</p><h1>{r.character} Â· {r.mode}</h1><p>{sm.state} Â· generation {r.generation} Â· seed {snapshot.seed}</p></div><div className="diagnostic-actions"><button onClick={()=>window.pokoloko.sendWindowCommand({type:'diagnostics_export_trace'})}>Export trace</button><button onClick={()=>window.pokoloko.sendWindowCommand({type:'diagnostics_replay_trace'})}>Replay trace</button><button onClick={()=>send({type:'reset_runtime'})}>Reset</button></div></header>
  <section className="diagnostic-grid">
   <article className="diagnostic-card"><h2>Presentation</h2><dl><dt>Animation</dt><dd>{p.animationId}</dd><dt>Frame</dt><dd>{(snapshot.lastAnimationEvent as any)?.frameIndex??'â€”'} / {p.frames.length-1}</dd><dt>FPS</dt><dd>{p.fps.toFixed(2)}</dd><dt>Direction</dt><dd>{p.locomotion.direction}</dd><dt>Movement</dt><dd>{p.locomotion.state} Â· {p.locomotion.speedPxPerSecond.toFixed(1)} px/s</dd><dt>Window</dt><dd>{snapshot.windowBounds.x}, {snapshot.windowBounds.y} Â· {snapshot.windowBounds.width}Ã—{snapshot.windowBounds.height}</dd><dt>Display</dt><dd>{snapshot.display.id} Â· {snapshot.display.scaleFactor}Ã—</dd><dt>Anchor</dt><dd>{p.anchor.x}, {p.anchor.y}</dd></dl><label className="diag-check"><input type="checkbox" checked={showGuides} onChange={e=>setShowGuides(e.target.checked)}/> Show guide values</label>{showGuides&&<pre>canvas 128Ã—128\nground {p.anchor.x},{p.anchor.y}\nbody {p.bodyCenter?`${p.bodyCenter.x},${p.bodyCenter.y}`:'not supplied'}\ndestination {p.locomotion.destinationX.toFixed(1)}</pre>}</article>
   <article className="diagnostic-card"><h2>Mind</h2><div className="mind-bars">{Object.entries(r.mind).filter(([,v])=>typeof v==='number'&&v<=1).map(([k,v])=><div key={k}><span>{k}</span><meter min="0" max="1" value={v as number}/><strong>{pct(v as number)}</strong></div>)}</div><div className="inline-controls"><select value={mindKey} onChange={e=>setMindKey(e.target.value)}>{['energy','playfulness','focus','sociability','curiosity','comfort','boredom','recentAttention','interruptionLoad'].map(k=><option key={k}>{k}</option>)}</select><input type="range" min="0" max="1" step=".05" value={mindValue} onChange={e=>setMindValue(Number(e.target.value))}/><button onClick={()=>send({type:'set_mind',patch:{[mindKey]:mindValue}})}>Apply</button></div></article>
   <article className="diagnostic-card"><h2>Current life</h2><dl><dt>Previous</dt><dd>{r.previousMode??'â€”'}</dd><dt>Active</dt><dd>{r.activeId??'none'}</dd><dt>Activity</dt><dd>{r.activity?`${r.activity.id} / ${r.activity.phase}`:'none'}</dd><dt>Prop</dt><dd>{r.activity?.propVisible?(r.activity.activePropId??'composite visible'):'none'}</dd><dt>Sleep</dt><dd>{r.sleep?.phase??'awake'}</dd><dt>Next plan</dt><dd>{r.nextPlanAtMonotonicMs?`${Math.max(0,r.nextPlanAtMonotonicMs-snapshot.capturedAtMonotonicMs).toFixed(0)} ms`:'not scheduled'}</dd><dt>Last decision</dt><dd>{r.lastDecisionReason??'â€”'}</dd></dl></article>
   <article className="diagnostic-card diagnostic-controls"><h2>Force behavior</h2><div className="button-wrap"><button onClick={()=>send({type:'force_idle',durationMs:6000})}>Idle</button>{(['left','center','right'] as const).map(region=><button key={region} onClick={()=>send({type:'force_walk',region})}>Walk {region}</button>)}<button onClick={()=>send({type:'force_sleep',durationMs:30000})}>Sleep</button><button onClick={()=>send({type:'force_wake'})}>Wake</button><button onClick={()=>send({type:'force_reaction',reaction:'click'})}>Click reaction</button><button onClick={()=>send({type:'force_reaction',reaction:'double_click'})}>Warm reaction</button></div><h3>Activities</h3><div className="button-wrap">{(['drink','eat','laptop','music','peeking','playing_ball','reading'] as const).map(activityId=><button key={activityId} onClick={()=>send({type:'force_activity',activityId,durationMs:12000})}>{activityId.replace('_',' ')}</button>)}</div><h3>Context</h3><div className="button-wrap"><button onClick={()=>send({type:'set_context',patch:{typingActivity:'sustained'}})}>Typing active</button><button onClick={()=>send({type:'set_context',patch:{fullscreenActive:true}})}>Fullscreen</button><button onClick={()=>send({type:'set_context',patch:{screenLocked:true}})}>Locked</button><button onClick={()=>send({type:'set_context',patch:{typingActivity:'none',fullscreenActive:false,screenLocked:false,systemIdle:false,audioActive:false}})}>Clear context</button></div><h3>System</h3><div className="button-wrap"><button onClick={()=>send({type:'set_character',character:r.character==='poko'?'loko':'poko'})}>Switch character</button><button onClick={()=>send({type:'set_paused',paused:r.mode!=='paused'})}>{r.mode==='paused'?'Resume':'Pause'}</button><button onClick={()=>send({type:'stop_movement'})}>Stop movement</button><button onClick={()=>send({type:'complete_drag'})}>Complete drag</button><button onClick={()=>send({type:'simulate_display_change'})}>Display change</button></div><div className="inline-controls"><input value={seed} onChange={e=>setSeed(e.target.value)} aria-label="Seed"/><button onClick={()=>send({type:'set_seed',seed:Number(seed)>>>0})}>Set seed</button></div></article>
  </section>
  <section className="diagnostic-lower"><article className="diagnostic-card"><h2>Planner scoring</h2><table><thead><tr><th>Candidate</th><th>Score</th><th>Reasons</th></tr></thead><tbody>{(r.plannerCandidates??[]).map(c=><tr key={c.key}><td>{c.key}</td><td>{c.score.toFixed(3)}</td><td>{c.reasons.join(' Â· ')}</td></tr>)}</tbody></table></article><article className="diagnostic-card event-log"><h2>Event trace</h2>{events.map(e=><div key={e.sequence} className={`event ${e.severity}`}><code>#{e.sequence}</code><strong>{e.category}/{e.name}</strong><span>{e.monotonicMs.toFixed(0)} ms</span></div>)}</article></section>
 </main>
}
