import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { LivingRuntimeController, type LivingRuntimePort, type LivingRuntimeSnapshot } from '../../packages/pet-engine/orchestration/src/index.js';
class Port implements LivingRuntimePort { animations:string[]=[]; walks:string[]=[]; stops:string[]=[]; restores:string[]=[]; snapshots:LivingRuntimeSnapshot[]=[]; async playAnimation(id:string){this.animations.push(id)} async restoreIdle(r:string){this.restores.push(r)} async walkToRegion(r:'left'|'center'|'right'){this.walks.push(r)} async stopMovement(r:string){this.stops.push(r)} log(){} onSnapshot(s:LivingRuntimeSnapshot){this.snapshots.push(s)} }
const settings={activityLevel:'balanced' as const,paused:false,quietMode:false,contextualAwareness:true};
describe('critical runtime paths with fake clocks',()=>{
 beforeEach(()=>vi.useFakeTimers({now:1000})); afterEach(()=>vi.useRealTimers());
 it('idle → walk → stop → idle',async()=>{const p=new Port(),r=new LivingRuntimeController('poko',settings,p,1);await r.forceIntention({kind:'walk',destinationRegion:'right',durationMs:1000});expect(r.snapshot().mode).toBe('walking');await r.onMovementFinished();expect(r.snapshot().mode).toBe('idle');r.dispose();});
 it('idle → sleep → wake → idle',async()=>{const p=new Port(),r=new LivingRuntimeController('poko',settings,p,2);await r.forceIntention({kind:'sleep',durationMs:95000});await r.onAnimationEvent({type:'ANIMATION_COMPLETED',animationId:'poko_sleep_transition',generation:1});await r.onSocialInput('click');await r.onAnimationEvent({type:'ANIMATION_COMPLETED',animationId:'poko_sleep_transition',generation:2});await vi.advanceTimersByTimeAsync(1000);expect(r.snapshot().mode).toBe('idle');r.dispose();});
 it('activity entry/loop/exit is safely cancelled by drag',async()=>{const p=new Port(),r=new LivingRuntimeController('loko',settings,p,3);await r.forceIntention({kind:'activity',activityId:'laptop',durationMs:10000});await vi.advanceTimersByTimeAsync(500);expect(r.snapshot().mode).toBe('activity');await r.onDragStarted();expect(r.snapshot().mode).toBe('dragged');expect(p.stops).toContain('drag');r.dispose();});
 it('character switch invalidates a mid-animation generation',async()=>{const p=new Port(),r=new LivingRuntimeController('loko',settings,p,4);await r.forceIntention({kind:'activity',activityId:'reading',durationMs:10000});const old=r.snapshot().generation;await r.switchCharacter('poko');expect(r.snapshot().character).toBe('poko');expect(r.snapshot().generation).toBeGreaterThan(old);expect(r.snapshot().activeId).toBeUndefined();r.dispose();});
 it('pause/resume and suspend-like restraint recover without timers sleeping',async()=>{const p=new Port(),r=new LivingRuntimeController('poko',settings,p,5);await r.forceIntention({kind:'walk',destinationRegion:'left',durationMs:1000});r.updateSettings({paused:true});await vi.runAllTimersAsync();expect(r.snapshot().mode).toBe('paused');r.updateSettings({paused:false});await vi.advanceTimersByTimeAsync(2500);expect(r.snapshot().mode).not.toBe('paused');r.dispose();});
});
